server:
  port: 8081
datapool:
  base-url: http://localhost:8080/api
spring:
  application:
    name: billing-service

resilience4j:
  circuitbreaker:
    instances:
      datapoolClient:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10